version: "3.8"

volumes:
  HNG-nginx-logs:        # named shared volume for logs
  nextcloud-data:        # Nextcloud persistent storage

services:

  nginx:
    image: nginx:alpine
    container_name: hng-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HNG-nginx-logs:/var/log/nginx          # nginx WRITES here
    depends_on:
      - nextcloud
    restart: unless-stopped

  nextcloud:
    image: kefaslungu/hng-nextcloud
    container_name: hng-nextcloud
    expose:
      - "80"                                   # internal only, NOT published
    volumes:
      - nextcloud-data:/var/www/html
      - HNG-nginx-logs:/var/log/nginx:ro       # read-only mount
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
    restart: unless-stopped

  detector:
    build:
      context: ./detector
      dockerfile: Dockerfile
    container_name: hng-detector
    network_mode: host
    cap_add:
      - NET_ADMIN        # gives iptables permission inside container
    privileged: true     # fallback if cap_add isn't enough
    volumes:
      - HNG-nginx-logs:/var/log/nginx:ro       # read-only mount
    depends_on:
      - nginx
    restart: unless-stopped
    # needs host network access for iptables (on the real server)
